### ISSUE TITLE
Persistent Back Button + more

### ISSUE THREAD

**Issue by simonrosted** [stephentuso/welcome-android#1]
Hi,

What an awesome project!

I'm using your library to create an instructional slide show, rather than using it as a conventional welcome screen. Therefore, I'd like to have persistently available back and forward buttons, and discard the skip and done buttons.

1. Is it possible to have a persistent back button, that can be used in a similar fashion to the forward button, allowing the user to navigate using a back and forward button in addition to swiping.
2. How do i allow for the activity to be "relaunched" after it has been "completed" by the user?
3. Is it possible to include a actionbar, allowing the user to navigate to the parent activity?

Thanks in advance!

**Comment by stephentuso** [comment]
Thanks!

I'm glad to hear it, that was one of the alternate uses I could see for this.

I was already thinking about adding a back button, so I just went ahead and did it. Update the library version to 0.6.0 and call `showPrevButton(true)` on the WelcomeScreenBuilder.

For relaunching it, calling `WelcomeScreenHelper.forceShow()` instead of `show()` might be what you're looking for.

To show an action bar, use a custom theme and add the following:
```
<item name="windowActionBar">true</item>
<item name="windowNoTitle">false</item>
```
By default the background will be transparent, but that can be changed. To show the back button in the action bar you'll have to call `showActionBarBackButton(true)` on the WelcomeScreenBuilder.

Maybe you already had this figured out, but to hide the skip button you'll have to disable skipping with `canSkip(false)`. That still allows the activity to be closed, but it doesn't "complete" it (will that be an issue?). 
To hide the done button call `useCustomDoneButton(true)` (I named it that to imply that you should add your own done button if you hide the provided one, that might not apply in your case though).

Let me know if that solves everything.

**Comment by simonrosted** [comment]
This is very very kind of you!! I'm very grateful!

Be aware that I have close no prior experience within android development (or any software development for that matter), so this is truly a test on the user friendliness of your library. So far it's all been very intuitive.

However, I have no success when trying to apply `.theme(int)` as seen in the screenshot below:
![screen shot 2016-01-31 at 11 35 07](https://cloud.githubusercontent.com/assets/8746591/12701630/ff386cfc-c80e-11e5-9d8e-811dd21a398e.png)
I've tried to replace `int` with `CustomWelcomeScreenTheme`, which is the name of the custom theme in `styles.xml`, but again without success.

On another matter, I'll suggest that title text is made aligned to top. If you on one screen have a title text that spans 2 lines, the placement of that text will be inconsistent to the remaining screens.


Again, thank you very much!

**Comment by stephentuso** [comment]
No problem!

It's good to hear this library has been intuitive. If this is your first coding project I'd definitely recommend doing some basic Java projects/tutorials before moving on to Android, at least that's what worked for me. I tried learning Android with absolutely no prior experience and nothing made sense, but after working with plain Java for a month or so and learning the basics of the language it started to click.

Anyway, the `int` in `.theme(int)` was intended to show the type of parameter the function takes. In this case, that `int` should be the *resource ID* of your theme. In Android, you access resources (everything in the 'res' folder) with resource IDs, which are generated automatically. See [Accessing 
resources](http://developer.android.com/guide/topics/resources/accessing-resources.html) on the developer site for more info. For your theme, you would call `.theme(R.style.CustomWelcomeScreenTheme)`.

I'll look into the titles when I have some time. The layouts could definitely use some improvements, I just haven't gotten around to it yet.
