### ISSUE TITLE
Back Button Issue

### ISSUE THREAD

**Issue by manishmas** [stephentuso/welcome-android#48]
When I click on Back button at that time welcome slider finish and next screen open.Not app close.

**Comment by stephentuso** [comment]
Listen to the activity result and exit your app on `RESULT_CANCELED` - see [Results in readme](https://github.com/stephentuso/welcome-android#results). You can also see it in the [demo code](https://github.com/stephentuso/welcome-android/blob/master/sample/src/main/java/com/stephentuso/welcomeexample/MainActivity.java#L76), instead of showing a toast you would call `finish()`.
